insert into public.beats (
  id, slug, title, description, bpm, key, genre, mood, tags, duration_sec,
  preview_url, wav_path, stems_path, status, cover_url, is_featured, sale_count, published_at
) values
(
  '00000000-0000-0000-0000-000000000001',
  'dark-trap-140-cmin',
  'Midnight Trap',
  'บีท Trap โทนมืด 808 หนัก เหมาะกับ hook ดุดันและ verse เร็ว',
  140,
  'C minor',
  'trap',
  array['dark', 'aggressive'],
  array['808', 'thai rap', 'club'],
  168,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'private/wav/dark-trap-140-cmin.wav',
  'private/stems/dark-trap-140-cmin.zip',
  'published',
  'https://picsum.photos/seed/webbeat-dark-trap-140-cmin/900/900',
  true,
  12,
  now()
),
(
  '00000000-0000-0000-0000-000000000002',
  'rnb-late-night-92-amin',
  'Late Night Calls',
  'R&B นุ่ม ๆ มี electric piano และ bass อุ่นสำหรับเพลงรักกลางคืน',
  92,
  'A minor',
  'rnb',
  array['smooth', 'romantic'],
  array['rnb', 'slow jam', 'vocal'],
  191,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'private/wav/rnb-late-night-92-amin.wav',
  'private/stems/rnb-late-night-92-amin.zip',
  'published',
  'https://picsum.photos/seed/webbeat-rnb-late-night-92-amin/900/900',
  true,
  7,
  now()
),
(
  '00000000-0000-0000-0000-000000000003',
  'drill-bangkok-144-dmin',
  'Bangkok Drill',
  'Drill pattern แน่น ๆ พร้อม slide bass สำหรับแร็ปไทยสาย street',
  144,
  'D minor',
  'drill',
  array['street', 'cold'],
  array['drill', 'slide bass', 'thai'],
  156,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  'private/wav/drill-bangkok-144-dmin.wav',
  'private/stems/drill-bangkok-144-dmin.zip',
  'published',
  'https://picsum.photos/seed/webbeat-drill-bangkok-144-dmin/900/900',
  false,
  19,
  now()
),
(
  '00000000-0000-0000-0000-000000000004',
  'boom-bap-sunset-86-fmin',
  'Sunset Cypher',
  'Boom bap / hip-hop คลาสสิก sample feel สำหรับ cypher และ storytelling',
  86,
  'F minor',
  'hiphop',
  array['nostalgic', 'warm'],
  array['boom bap', 'sample', 'cypher'],
  174,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  'private/wav/boom-bap-sunset-86-fmin.wav',
  null,
  'published',
  'https://picsum.photos/seed/webbeat-boom-bap-sunset-86-fmin/900/900',
  false,
  5,
  now()
),
(
  '00000000-0000-0000-0000-000000000005',
  'phonk-afterhours-138-gmin',
  'Afterhours Phonk',
  'Phonk bell พร้อม cowbell และ Memphis vibe เหมาะทำซ้อตไทยสายเมาโซตโครติก',
  138,
  'G minor',
  'trap',
  array['phonk', 'noir'],
  array['cowbell', 'memphis', 'phonk'],
  162,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  'private/wav/phonk-afterhours-138-gmin.wav',
  'private/stems/phonk-afterhours-138-gmin.zip',
  'published',
  'https://picsum.photos/seed/webbeat-phonk-afterhours-138-gmin/900/900',
  true,
  21,
  now()
),
(
  '00000000-0000-0000-0000-000000000006',
  'pluggnb-clouds-150-emaj',
  'Skyline Pluggnb',
  'Pluggnb airy chords พื้นที่สำหรับเมโลดี้สายโคโยตี้และโฟลว์ลอย',
  150,
  'E major',
  'rnb',
  array['dreamy', 'sparkly'],
  array['pluggnb', 'melodic'],
  178,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  'private/wav/pluggnb-clouds-150-emaj.wav',
  null,
  'published',
  'https://picsum.photos/seed/webbeat-pluggnb-clouds-150-emaj/900/900',
  false,
  9,
  now()
),
(
  '00000000-0000-0000-0000-000000000007',
  'club-thai-pop-126-amaj',
  'Bangkok Flood Lights',
  'โปรดักชันโทนป็อปไทยผสมแทรป เบสชัดและพื้นที่ร้อง chorus',
  126,
  'A major',
  'hiphop',
  array['bright', 'club'],
  array['thai pop', 'club', 'hook'],
  200,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'private/wav/club-thai-pop-126-amaj.wav',
  'private/stems/club-thai-pop-126-amaj.zip',
  'published',
  'https://picsum.photos/seed/webbeat-club-thai-pop-126-amaj/900/900',
  false,
  14,
  now()
),
(
  '00000000-0000-0000-0000-000000000008',
  'ghost-drill-148-fsharpmin',
  'Ghost Alley',
  'Drill เหมือนหลุดจากถนนตีบมุดใต้ไฟถนนขาวนวล',
  148,
  'F# minor',
  'drill',
  array['sinister', 'fast'],
  array['ghost', 'slide'],
  151,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  'private/wav/ghost-drill-148-fsharpmin.wav',
  null,
  'published',
  'https://picsum.photos/seed/webbeat-ghost-drill-148-fsharpmin/900/900',
  false,
  16,
  now()
),
(
  '00000000-0000-0000-0000-000000000009',
  'smoke-trap-134-bmin',
  'Smoke Signals',
  'Trap hi-hat สามชั้นพร้อม sub low ที่พุ่งชัดในลำโพงรถยนต์',
  134,
  'B minor',
  'trap',
  array['heavy', 'carti-ish'],
  array['trap', 'bounce'],
  169,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  'private/wav/smoke-trap-134-bmin.wav',
  'private/stems/smoke-trap-134-bmin.zip',
  'published',
  'https://picsum.photos/seed/webbeat-smoke-trap-134-bmin/900/900',
  false,
  28,
  now()
),
(
  '00000000-0000-0000-0000-000000000010',
  'lofi-story-78-dmaj',
  'Notebook Tape',
  'Lo-fi boom bap เบา ๆ สำหรับ storytelling และโฟลว์เปิดใจ',
  78,
  'D major',
  'hiphop',
  array['lofi', 'warm'],
  array['lofi', 'talkbox'],
  205,
  'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  'private/wav/lofi-story-78-dmaj.wav',
  null,
  'published',
  'https://picsum.photos/seed/webbeat-lofi-story-78-dmaj/900/900',
  false,
  4,
  now()
);

insert into public.beat_licenses (beat_id, tier, price_thb, terms)
select
  b.id,
  tier::license_tier,
  price,
  jsonb_build_object(
    'streamLimit', stream_limit,
    'monetization', monetization,
    'musicVideo', music_video,
    'livePerformance', true,
    'stemsIncluded', stems_included,
    'creditRequired', true,
    'exclusive', exclusive,
    'publishingSplit', jsonb_build_object('licensee', 50, 'producer', 50),
    'masterRights', jsonb_build_object(
      'beatMasterOwner', 'producer',
      'finalSongMasterOwner', 'licensee',
      'transferBeatMaster', false
    ),
    'files', files
  )
from public.beats b
cross join (
  values
    ('basic', 399, 5000, false, false, false, false, to_jsonb(array['MP3 untagged']::text[])),
    ('premium', 999, 50000, true, true, false, false, to_jsonb(array['WAV', 'MP3 untagged']::text[])),
    ('trackout', 2499, 100000, true, true, true, false, to_jsonb(array['WAV', 'MP3 untagged', 'Stems']::text[])),
    ('exclusive', 12000, null, true, true, true, true, to_jsonb(array['WAV', 'MP3 untagged', 'Stems']::text[]))
) as licenses(tier, price, stream_limit, monetization, music_video, stems_included, exclusive, files)
on conflict (beat_id, tier) do nothing;
